### ISSUE TITLE
Installing subject-package with invenioRDM crashes

### ISSUE THREAD

**Issue by ghost** [ulbmuenster/invenio-subjects-gnd#1]
1, Create invenio-Instanz

```
mkdir inv7
cd inv7
python3 -m venv venv
source venv/bin/activate
python -m pip install --upgrade pip
pip install invenio-cli
pip install Flask-Debugtoolbar
invenio-cli --version
invenio-cli check-requirements
invenio-cli init rdm -c v7.0
```

2. Add invenio-subjects-gnd package in Pipfile

```
vi Pipfile
```
```
...

[packages]
invenio-app-rdm = {extras = ["postgresql", "elasticsearch7"], version = "~=7.0.0"}
uwsgi = ">=2.0"
uwsgitop = ">=0.11"
uwsgi-tools = ">=1.1.1"

# Subjects gnd.
invenio-subjects-gnd = "*"

...
```

3. Container install

```
invenio-cli packages lock
invenio-cli containers build
invenio-cli containers setup
invenio-cli containers start
```

4. Failes at `invenio-cli containers setup`

```
(venv) 16:43:19 chriz@mr09202018n:~/rz/code/invenio/inv7/inv7$ invenio-cli containers setup
Setting up services with force False, demo data True and stop after setup False...
Making sure containers are up...
redis up and running!
postgresql up and running!
es up and running!
Containers started and healthy.
Creating database...
Creating database postgresql+psycopg2://inv7:***@db/inv7
Creating all tables!
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
Created all tables!
Creating files location...
Location default-location /opt/invenio/var/instance/data as default True stored in database
Creating admin role...
Role "admin" created successfully.
Assigning superuser access to admin role...
Creating indices...
Creating indexes...
requests  [####################################]  100%
Putting templates...
Updating service setup status (True)...
Service setup status updated (new value True).
Creating fixtures...
Failed to setup services.
Output: Creating required fixtures...
Traceback (most recent call last):
  File "/usr/local/lib64/python3.8/site-packages/yaml/reader.py", line 89, in peek
    return self.buffer[self.pointer+index]
IndexError: string index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/invenio", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 600, in main
    return super().main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 444, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/invenio_rdm_records/cli.py", line 48, in create_fixtures
    FixturesEngine(system_identity).run()
  File "/usr/local/lib/python3.8/site-packages/invenio_rdm_records/fixtures/__init__.py", line 32, in run
    PrioritizedVocabulariesFixtures(
  File "/usr/local/lib/python3.8/site-packages/invenio_rdm_records/fixtures/vocabularies.py", line 202, in load
    self.load_from_extensions()
  File "/usr/local/lib/python3.8/site-packages/invenio_rdm_records/fixtures/vocabularies.py", line 233, in load_from_extensions
    self.load_vocabularies(filepath)
  File "/usr/local/lib/python3.8/site-packages/invenio_rdm_records/fixtures/vocabularies.py", line 253, in load_vocabularies
    self._loaded_vocabularies = fixture.load(
  File "/usr/local/lib/python3.8/site-packages/invenio_rdm_records/fixtures/vocabularies.py", line 313, in load
    entry.load(self._identity, ignore=ids, delay=self._delay)
  File "/usr/local/lib/python3.8/site-packages/invenio_rdm_records/fixtures/vocabularies.py", line 333, in load
    for data in self.iterate(ignore=ignore):
  File "/usr/local/lib/python3.8/site-packages/invenio_rdm_records/fixtures/vocabularies.py", line 403, in iterate
    yield from create_iterator(filepath)
  File "/usr/local/lib/python3.8/site-packages/invenio_rdm_records/fixtures/vocabularies.py", line 47, in __iter__
    data = yaml.safe_load(fp) or []
  File "/usr/local/lib64/python3.8/site-packages/yaml/__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "/usr/local/lib64/python3.8/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/usr/local/lib64/python3.8/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/usr/local/lib64/python3.8/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/local/lib64/python3.8/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/local/lib64/python3.8/site-packages/yaml/composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/usr/local/lib64/python3.8/site-packages/yaml/composer.py", line 111, in compose_sequence_node
    node.value.append(self.compose_node(node, index))
  File "/usr/local/lib64/python3.8/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib64/python3.8/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/local/lib64/python3.8/site-packages/yaml/composer.py", line 64, in compose_node
    if self.check_event(AliasEvent):
  File "/usr/local/lib64/python3.8/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/local/lib64/python3.8/site-packages/yaml/parser.py", line 449, in parse_block_mapping_value
    if not self.check_token(KeyToken, ValueToken, BlockEndToken):
  File "/usr/local/lib64/python3.8/site-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/usr/local/lib64/python3.8/site-packages/yaml/scanner.py", line 251, in fetch_more_tokens
    return self.fetch_double()
  File "/usr/local/lib64/python3.8/site-packages/yaml/scanner.py", line 655, in fetch_double
    self.fetch_flow_scalar(style='"')
  File "/usr/local/lib64/python3.8/site-packages/yaml/scanner.py", line 666, in fetch_flow_scalar
    self.tokens.append(self.scan_flow_scalar(style))
  File "/usr/local/lib64/python3.8/site-packages/yaml/scanner.py", line 1149, in scan_flow_scalar
    chunks.extend(self.scan_flow_scalar_non_spaces(double, start_mark))
  File "/usr/local/lib64/python3.8/site-packages/yaml/scanner.py", line 1190, in scan_flow_scalar_non_spaces
    while self.peek(length) not in '\'\"\\\0 \t\r\n\x85\u2028\u2029':
  File "/usr/local/lib64/python3.8/site-packages/yaml/reader.py", line 91, in peek
    self.update(index+1)
  File "/usr/local/lib64/python3.8/site-packages/yaml/reader.py", line 169, in update
    self.check_printable(data)
  File "/usr/local/lib64/python3.8/site-packages/yaml/reader.py", line 143, in check_printable
    raise ReaderError(self.name, position, ord(character),
yaml.reader.ReaderError: unacceptable character #x0098: special characters are not allowed
  in "/usr/local/lib/python3.8/site-packages/invenio_subjects_gnd/vocabularies/subjects_gnd.yaml", position 18639
```

**Comment by wgresshoff** [comment]
Die Ursache sind nicht druckbare/sichtbare Zeichen, die in YAML nicht erlaubt sind.

**Comment by wgresshoff** [comment]
New version uploaded to PyPi
